version: '3.8'

services:
  # ✅ Express API Service
  api:
    build: ./backend
    container_name: bike-api
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app

  # ✅ Next.js Frontend
  frontend:
    build: ./frontend
    container_name: bike-frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - api
    ports:
      - "3000:3000"

  # ✅ Python Scraper (Runs Once a Day)
  scraper:
    build: ./scraper
    container_name: bike-scraper
    restart: "always"
    command: ["python", "scripts/trek.py"]
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/letsencrypt