version: '3.8'

services:
  # ✅ Express API Service
  api:
    build: ./backend
    container_name: bike-api
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app

  # ✅ Next.js Frontend
  frontend:
    build: ./frontend
    container_name: bike-frontend
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    ports:
      - "3000:3000"