MONGO_URI ="mongodb+srv://lucaspierru7:s1DvPr0m0L9Ftnob@dev.yj06k.mongodb.net/bike-comparator?retryWrites=true&w=majority&appName=Dev&tls=true"
DB_NAME = "bike-comparator"
COLLECTION_NAME = "bikes"
BRANDS_LIST = [
  {"name": "Trek", "website": "https://www.trekbikes.com"},
  {"name": "Specialized", "website": "https://www.specialized.com"},
  {"name": "Giant", "website": "https://www.giant-bicycles.com"},
  {"name": "Cannondale", "website": "https://www.cannondale.com"},
  {"name": "Santa Cruz", "website": "https://www.santacruzbicycles.com"},
  {"name": "Scott", "website": "https://www.scott-sports.com"},
  {"name": "Canyon", "website": "https://www.canyon.com"},
  {"name": "Bianchi", "website": "https://www.bianchi.com"},
  {"name": "Orbea", "website": "https://www.orbea.com"},
  {"name": "BMC", "website": "https://www.bmc-switzerland.com"},
  {"name": "Merida", "website": "https://www.merida-bikes.com"},
  {"name": "Fuji", "website": "https://www.fujibikes.com"},
  {"name": "Kona", "website": "https://www.konaworld.com"},
  {"name": "Pivot", "website": "https://www.pivotcycles.com"},
  {"name": "Yeti Cycles", "website": "https://www.yeticycles.com"},
  {"name": "Niner", "website": "https://www.ninerbikes.com"},
  {"name": "Revel Bikes", "website": "https://www.revelbikes.com"},
  {"name": "Ibis", "website": "https://www.ibiscycles.com"},
  {"name": "Cervélo", "website": "https://www.cervelo.com"},
  {"name": "Colnago", "website": "https://www.colnago.com"},
  {"name": "Factor", "website": "https://www.factorbikes.com"},
  {"name": "Argon 18", "website": "https://www.argon18.com"},
  {"name": "Wilier", "website": "https://www.wilier.com"},
  {"name": "Ribble", "website": "https://www.ribblecycles.co.uk"},
  {"name": "Felt", "website": "https://www.feltbicycles.com"},
  {"name": "Pinarello", "website": "https://www.pinarello.com"},
  {"name": "Look", "website": "https://www.lookcycle.com"},
  
  {"name": "Shimano", "website": "https://www.shimano.com"},
  {"name": "SRAM", "website": "https://www.sram.com"},
  {"name": "Campagnolo", "website": "https://www.campagnolo.com"},
  {"name": "FSA (Full Speed Ahead)", "website": "https://www.fullspeedahead.com"},
  {"name": "Rotor", "website": "https://rotorbike.com"},
  {"name": "Hope Technology", "website": "https://www.hopetech.com"},
  {"name": "ENVE", "website": "https://www.enve.com"},
  {"name": "Zipp", "website": "https://www.sram.com/en/zipp"},
  {"name": "DT Swiss", "website": "https://www.dtswiss.com"},
  {"name": "Mavic", "website": "https://www.mavic.com"},
  {"name": "Chris King", "website": "https://www.chrisking.com"},
  {"name": "Thomson", "website": "https://www.bikethomson.com"},
  {"name": "Race Face", "website": "https://www.raceface.com"},
  {"name": "Fox Racing Shox", "website": "https://www.ridefox.com"},
  {"name": "RockShox", "website": "https://www.sram.com/en/rockshox"},
  {"name": "Magura", "website": "https://www.magura.com"},
  {"name": "TRP Brakes", "website": "https://trpcycling.com"},
  {"name": "Wheels Manufacturing", "website": "https://wheelsmfg.com"},
  {"name": "OneUp Components", "website": "https://www.oneupcomponents.com"},
  {"name": "Ergon", "website": "https://www.ergonbike.com"},
  {"name": "SDG Components", "website": "https://www.sdgcomponents.com"},
  {"name": "Spank", "website": "https://www.spank-ind.com"},
  {"name": "Crankbrothers", "website": "https://www.crankbrothers.com"},
  {"name": "KMC", "website": "https://www.kmcchain.com"},
  
  {"name": "3T Cycling", "website": "https://www.3t.bike"},
  {"name": "absoluteBLACK", "website": "https://absoluteblack.cc"},
  {"name": "Acros", "website": "https://acros-components.com"},
  {"name": "Atala", "website": "https://www.atala.it"},
  {"name": "Avid", "website": "https://www.sram.com/en/avid"},
  {"name": "Baisikeli Ugunduzi", "website": "https://www.baisikeliugunduzi.com"},
  {"name": "Bell", "website": "https://www.bellhelmets.com"},
  {"name": "Bike Arc", "website": "https://www.bikearc.com"},
  {"name": "Bontrager", "website": "https://www.trekbikes.com/bontrager"},
  {"name": "Bosch", "website": "https://www.bosch-ebike.com"},
  {"name": "Brooks Saddle", "website": "https://www.brooksengland.com"},
  {"name": "Burley Design", "website": "https://www.burley.com"},
  {"name": "Cadex", "website": "https://www.cadex-cycling.com"},
  {"name": "Cheng Shin Rubber", "website": "https://www.csttires.com"},
  {"name": "Chris King", "website": "https://chrisking.com"},
  {"name": "Cinelli", "website": "https://cinelli.it"},
  {"name": "Coker Tire", "website": "https://www.cokertire.com"},
  {"name": "Columbus", "website": "https://www.columbustubi.com"},
  {"name": "Continental", "website": "https://www.continental-tires.com"},
  {"name": "Cane Creek", "website": "https://www.canecreek.com"},
  {"name": "Dia-Compe", "website": "http://www.dia-compe.com"},
  {"name": "Easton", "website": "https://eastoncycling.com"},
  {"name": "e*thirteen", "website": "https://www.ethirteen.com"},
  {"name": "Fulcrum Wheels", "website": "https://www.fulcrumwheels.com"},
  {"name": "Gabaruk", "website": "https://www.garbaruk.com"},
  {"name": "Garmin", "website": "https://www.garmin.com"},
  {"name": "Gates Corporation", "website": "https://www.gates.com"},
  {"name": "Giro", "website": "https://www.giro.com"},
  {"name": "Gary Fischer", "website": "https://www.trekbikes.com/gary_fisher"},
  {"name": "HED", "website": "https://hedcycling.com"},
  {"name": "Hutchinson", "website": "https://www.hutchinsontires.com"},
  {"name": "Lightweight", "website": "https://lightweight.info"},
  {"name": "Look", "website": "https://www.lookcycle.com"},
  {"name": "Mafac", "website": "https://www.velobase.com/ViewBrand.aspx?BrandID=6af1b0d0-3b8d-4b3b-9b3b-0b1c3b0b0b0b"},
  {"name": "Marzocchi", "website": "https://www.marzocchi.com"},
  {"name": "Maxxis", "website": "https://www.maxxis.com"},
  {"name": "Michelin", "website": "https://www.michelin.com"},
  {"name": "Reynolds", "website": "https://reynoldstechnology.biz"},
  {"name": "Sachs", "website": "https://www.sachs-bikes.de"},
  {"name": "Schwalbe", "website": "https://www.schwalbe.com"},
  {"name": "Selle Italia", "website": "https://www.selleitalia.com"},
  {"name": "Speedplay", "website": "https://www.wahoofitness.com/speedplay"},
  {"name": "SwissStop", "website": "https://www.swissstop.ch"},
  {"name": "Vittoria", "website": "https://www.vittoria.com"},
  {"name": "Wahoo", "website": "https://www.wahoofitness.com"},
  {"name": "Zipp", "website": "https://www.sram.com/en/zipp"}
]
